### ISSUE TITLE
Minipets on SkyBlock

### ISSUE THREAD

**Issue by NachtRaben** [NachtRaben/AliACraft-Issues#1]
Pheonix_Magic:
Jack was going to add mini pets to skyblock (Ollieed said we weren't allowed it cause survival had it) but then we came to the conclusion that skyblock could have Mini pets IF we had custom pets. Now, Idk how to make these custom pets

**Comment by Dooleylabs** [comment]
All extensions of this issue are to be posted in #36, where I've listed all worked expected to be done to Skyblock.

**Comment by ollieblac** [comment]
(Ollieed said we weren't allowed it cause survival had it) huh? Wat
