### ISSUE TITLE
Arcade: Micro Battles Countdown

### ISSUE THREAD

**Issue by FPS-Skilled** [NachtRaben/AliACraft-Issues#12]
There are two issues with the countdown in Micro Battles.

The first issue involves the countdown for the walls to drop after the game has started. The walls seem to drop rather quick once the game has started and would help if it were extended a little more. Right now players can only mine a couple blocks before the walls actually drop.

The second issue is that Micro Battles doesn't seem to have a game countdown or a time limit, so games can run on for a very long time. Normally this wouldn't be an issue with world degeneration implemented, but Micro Battles does not have that at the moment (created an issue thread for this  #7 )

**Comment by Yeetman** [comment]
First point: That's how it's really supposed to be. The time should be staying at that estimated amount of time before the walls fall down

Second Point: The only gamemode that should be having a time limit, is UHC.
