### ISSUE TITLE
Arcade: SkyWars Scarce Weapons

### ISSUE THREAD

**Issue by FPS-Skilled** [NachtRaben/AliACraft-Issues#15]
In SkyWars, if the OP option is not selected, weapons are very scarce (not that kind of scarce, Yeetman lol) and hard to find. This can put players at big disadvantages if they do not spawn with some sort of weapon from their beginning chests. This issue only happens in the standard, non OP, style of SkyWars and happens frequently.

**Comment by MrWarHawkk** [comment]
It has happened to me in OP as well
