### ISSUE TITLE
Arcade: Micro Battles & SkyWars /force Issue

### ISSUE THREAD

**Issue by FPS-Skilled** [NachtRaben/AliACraft-Issues#21]
The /force in both Micro Battles and SkyWars is not instant pre-game. You do /force and it doesn't start the game until 1-2m later. The /force command is instant when you do it on UHC and HG and it would be great if it could also be instant on SkyWars and Micro Battles. It just helps to move games along quicker without having to wait an undetermined amount of time for the games to start.

**Comment by MrWarHawkk** [comment]
According to yeet it's meant to be like that

**Comment by MrWarHawkk** [comment]
I would prefer it to be instant

**Comment by Dooleylabs** [comment]
**RIP in peace AliaCraft Arcade - October 5, 2016**
