### ISSUE TITLE
Arcade: Hub Mini-game Selector/NCP's

### ISSUE THREAD

**Issue by FPS-Skilled** [NachtRaben/AliACraft-Issues#22]
In the Arcade Hub there is a mini-game selector where you can select which mini-game you want to play, as well as specific lobbies. There are also NCP's in front of the mini-game portals which allow you to select specific mini-game lobbies. For both the mini-game selector and the NCP's, they don't correctly show which lobbies are open, in progress, restarting, or how many players are in each game. This can be beneficial to show players which lobbies they can join without having to use the portal.

**Comment by Dooleylabs** [comment]
**RIP in peace AliaCraft Arcade - October 5, 2016**
