### ISSUE TITLE
Arcade: Hunger Games Unfinished Map

### ISSUE THREAD

**Issue by FPS-Skilled** [NachtRaben/AliACraft-Issues#23]
This issue is not a big one but it has been brought up that the HG map "HG1_temp" has some tree formations right near the spawn that are supposed to be mushroom trees that are unfinished. Instead of mushrooms, there is sponge placed from where somebody was using w/e to spawn in the mushrooms on the trees. I did not get to explore more of the map, so I am unsure if this happens elsewhere.

**Comment by Dooleylabs** [comment]
**RIP in peace AliaCraft Arcade - October 5, 2016**
