### ISSUE TITLE
Creative lag

### ISSUE THREAD

**Issue by JamieNan** [NachtRaben/AliACraft-Issues#24]
There is a lot of lag on Creative, mainly after you've tp'd or warped somewhere. Players experience around a 5-15 second delay before they can do anything e.g type in chat, move properly, break blocks and place blocks after warping or tping somewhere.

**Comment by Dooleylabs** [comment]
I'm scheduling some maintenance to be done on Creative one of these days. For now, the lag _should_ be fixed, but if not, feel free to reopen this issue @JamieNan.
