### ISSUE TITLE
Arcade: Addition of Games in Progress in the games selector

### ISSUE THREAD

**Issue by MrWarHawkk** [NachtRaben/AliACraft-Issues#25]
Would it be possible if we could see all the games that are in progress through the games selector much like we did in the previous arcade. 

Games in progress were indicated by the red wool and games that had not started were the green wool.

It would be beneficial when trying to catch hackers, because the current /folo command isn't the most reliable due to most players not knowing the full ign of the hacker.

**Comment by Dooleylabs** [comment]
**RIP in peace AliaCraft Arcade - October 5, 2016**
