### ISSUE TITLE
Players able to bypass not being able to use /msg or /r while muted on prison

### ISSUE THREAD

**Issue by appsbytom** [NachtRaben/AliACraft-Issues#26]
People use /er /w /t and many other variants while muted to message and annoy socialspy. They use these because they cant /r so i don't think they should be able to use these others. It makes it annoying as people don't care about being muted as they can still talk to use and annoy mods upwards. Therefore they say what gets them muted as they can still talk.
Thanks.

btw this is on both chaos and classic prison.

**Comment by Dooleylabs** [comment]
Ben's on it

**Comment by Dooleylabs** [comment]
I'll be checking this and close the issue if it's been finished. If it's not, I'll get on it... or get @BenBeast on it.

**Comment by Benkers** [comment]
Fixed.
