### ISSUE TITLE
Skyblock: Blazes and squids not working correctly

### ISSUE THREAD

**Issue by whitey212** [NachtRaben/AliACraft-Issues#27]
On slyblock blazes stopped taking water damage and squids don't fall anymore like they are supposed to in squid grinders.

**Comment by Dooleylabs** [comment]
Think that's called a broken server. There's nothing I'm aware of that can do that.

**Comment by whitey212** [comment]
Obviously something has happened, Everything was fine a week ago.

**Comment by NachtRaben** [comment]
This is due to tick bypassing to prevent the server from lagging out due to spawned entities.
I'll look into tweaking the values to make this alittle more fluid.

**Comment by Dooleylabs** [comment]
I've tweaked spawning values to help lessen the load on the server.

**Comment by Dooleylabs** [comment]
Should be fixed. I'm closing this issue. If it's still a problem, post a comment here: #36
