### ISSUE TITLE
Arcade: SkyWars - Knocking players off

### ISSUE THREAD

**Issue by MrWarHawkk** [NachtRaben/AliACraft-Issues#30]
When you knock players off islands on skywars you don't always get the kill, instead it just says they died.

**Comment by Dooleylabs** [comment]
Have you tried actually killing them?

**Comment by MrWarHawkk** [comment]
Yeah, but you knocking players off is inevitable in skywars, like when you use projectiles or the axes with knockback on them.

**Comment by Dooleylabs** [comment]
**RIP in peace AliaCraft Arcade - October 5, 2016**
