### ISSUE TITLE
The q shop villagers have despawned on survival

### ISSUE THREAD

**Issue by jackdozza** [NachtRaben/AliACraft-Issues#31]
Can the villagers on survival for q shop at spawn be re done because they have despanwed and atm non donors cant buy or sell anything making it near impossible for them to progress on survival. Cheers!:D

**Comment by Dooleylabs** [comment]
It's a known issue with Clearlag. It'll be dealt with.

**Comment by NachtRaben** [comment]
@Dooleylabs Has this been addressed yet?

**Comment by Dooleylabs** [comment]
Wasn't my job to deal with it xD
Assign it to Ben._.

**Comment by Benkers** [comment]
It is fixed.
