### ISSUE TITLE
Arcade: Vote-to-Start for Players

### ISSUE THREAD

**Issue by FPS-Skilled** [NachtRaben/AliACraft-Issues#32]
This is just a suggestion for the mini-games in Arcade. I had a player suggest that a vote-to-start system be implemented into Arcade so that the mini-games can start if there does not happen to be enough players to have a full game, or if there are no staff online to force the games for them. I think this would be a good idea to add because it can speed up the process of starting/playing games for players and let them have a more enjoyable experience.

**Comment by Benkers** [comment]
I like that, but it'll be after we finish a few other things, thanks though!
