### ISSUE TITLE
Need a few warps for classic

### ISSUE THREAD

**Issue by mitchka21** [NachtRaben/AliACraft-Issues#33]
I have made a maze for a Halloween event and would like a warp added 1st to paper so that players that get an early access ticket can right click and go there  then ill need a warp for the rest of the players  once the early access is over. also i hold other events  that will be helpful to have a warp for so im not having to tp players all the time.

**Comment by Dooleylabs** [comment]
Is that even possible._.

**Comment by NachtRaben** [comment]
I can address this before Halloween Mitchka.

**Comment by mitchka21** [comment]
we were hoping to do this next sunday if possible if not then show me how to set warps and  add them to the players we can tp the ones with tickets

**Comment by mitchka21** [comment]
if not  we can do another event to give you time

**Comment by NachtRaben** [comment]
I can get it done in this week more n likely.

**Comment by mitchka21** [comment]
thanks

**Comment by NachtRaben** [comment]
Plugin has been created.
