### ISSUE TITLE
Factions Envoys

### ISSUE THREAD

**Issue by MintyOG** [NachtRaben/AliACraft-Issues#34]
Hello Minty here, just wondering if anyone  could get around to fixing factions envoys as currently only around 15-20 actually spawn out of a possible 50. They spawn around the warzone and this issue has been here for about 2 weeks now. Thanks in advance :D

**Comment by Benkers** [comment]
I will fix this in the next few days with Mikey.

**Comment by Benkers** [comment]
THIS IS NOW FIXED!
