### ISSUE TITLE
Factions Mob Boss

### ISSUE THREAD

**Issue by MintyOG** [NachtRaben/AliACraft-Issues#35]
Factions Mob boss seems to be a bit glitched because when you kill it, it kicks everyone who is around you off the server, and if you are in combat you instantly die. This issue was only brought to my intention today by a fellow staff member so I do not know if this will still be a factor in a while but I will keep you updated

**Comment by Benkers** [comment]
This is a glitch with the recent issues we've had with the network, this will be fixed soon.
