### ISSUE TITLE
[Skyblock] Issue List from Update | October 4, 2016

### ISSUE THREAD

**Issue by Dooleylabs** [NachtRaben/AliACraft-Issues#36]
Over the course of nine hours, I've lowered the spawning rate of spawners and adjusted many configuration nodes across all 75-ish plugins on the server. Several things were wrongly configured and have been adjusted to fight TPS spikes. The last cause of TPS spikes seems to be caused by the world save event, which is possibly correctable. As for the 75 plugins on the server, at least 45 of them have been updated to their latest versions since they hadn't been updated since early August.

Below is a _small_ todo list of what needs to be done:
- [x] Adjust spawing rates to spawn more animals, less mobs, and relieve TPS stress | #27 
- [x] Change default group's chat from gray to white
- [x] Adjust the timeout of the `/fix` command
- [x] Add permission to remove items from AuctionHouse to admins
- [x] Give access to colored nickname formatting to donor6 and staff
- [x] Enable spider stacking
- [x] Disable chunk garbage collector and bukkit's automatic world saving
- [x] Address ClearLag not broadcasting initial cleanup
- [x] Fix chat formatting of groups with `"*"` permissions
- [x] Deal with possible broken NPCs as they do not seem to be click-able
- [x] Disable enderpearls in the pvp arena / world [while in combat]
- [x] Rank name updates and changes
- [x] Fix the fact that a glow color overrides tab prefix + name formatting **[DISABLED]**
- [x] Fixed enderman mob stacking
- [x] Colorify the donor prefixes [[http://imgur.com/a/C22HT](http://imgur.com/a/C22HT)]
- [x] Figure out why some players spawner level tag is missing, though the perm exists
- [ ] Figure out why `/block` and `/pot` no longer exist, but their aliases do
- [ ] Once monthly maze completion prizes
- [ ] Token system for in-game perks
- [ ] A minipets buycraft perk | #1 
- [ ] Add Lockette or find a proper chestshop plugin
- [ ] Add `/warp market` back to the server / find and fix it's plugin
- [ ] Update the challenges list and reset player progress of them
- [ ] Tags?

About #27: I changed many spawning values to deal with over-spawning in chunks, which should add a little more distribution to the amount of mobs spawning and where they spawn. As for squids, they do not spawn above a certain level, and to change that would be deadly for the server. It's not a vanilla value we can manipulate anymore.

Should this update have generated any new bugs, they should be listed here.

**Comment by ollieblac** [comment]
I am working on 'Fix the fact that a glow color overrides tab prefix + name formatting' i've asked the dev to change some perms so that should be fixed soon.

**Comment by twestin74** [comment]
Endermen don't stack anymore from spawners

**Comment by Dooleylabs** [comment]
And now they do.

**Comment by twestin74** [comment]
You are the man thank you for all you do Dooley
