### ISSUE TITLE
Votes - Don't seem to be coming through

### ISSUE THREAD

**Issue by ollieblac** [NachtRaben/AliACraft-Issues#37]
When people vote on the US addresses the votes aren't actually coming through in-game. Can we get this fixed?

**Comment by Dooleylabs** [comment]
This is an issue for Ben. They come through on the EU proxy without issue. The US proxy seems to be slow - I've had reports that voting for / using mc.aliacraft.net seems to help.

**Comment by ollieblac** [comment]
I've been using us.aliacraft.net and voting on the US links but they're not working.

**Comment by Dooleylabs** [comment]
The votes are coming into the bungee, but not going to the servers. Ben, you're up.

**Comment by NachtRaben** [comment]
If you can physically connect to the server you're voting on then there is no reason why they shouldn't be getting lost when being recieved .-. ben is using plugin channels, right?

**Comment by Benkers** [comment]
Its working now, thanks whoever fixed it :D

**Comment by Dooleylabs** [comment]
Lol think it was when we reset the db! xD

**Comment by Benkers** [comment]
Yup! Really pleased! :D
