### ISSUE TITLE
Mods and higher cant see other vanished staff

### ISSUE THREAD

**Issue by appsbytom** [NachtRaben/AliACraft-Issues#38]
On chaos when mods vanish they cannot be seen by any staff. This is very annoying if you are trying to get help for something and you cant see if theres any other staff on but in vanish. Ikd why it changed, it never used to be like this.
Thanks

**Comment by Dooleylabs** [comment]
Far as I know, mods could never see other staff in vanish, and as for higher ups not seeing them, you are using /v correct? Not /ev? Ben fix this._. I haven't gotten to prison yet.

**Comment by Benkers** [comment]
Only admins should be able to see other members of staff in vanish.

**Comment by appsbytom** [comment]
but admins cant see others in vanish... no one can

**Comment by Benkers** [comment]
Ok I will fix this.

**Comment by appsbytom** [comment]
Also because mods cant see other staff in /v if theres a hacker and they need help to record we cant tp to the staff as they r not in tab.

**Comment by Dooleylabs** [comment]
And that's intentional. If someone's hacking, you tp to the hacker, not the staff member.
